spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tx-interview?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: password
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
endpoints:
  flyway:
    enabled: true